Make posix compliant and use awk sub/gsub
- Use /bin/sh instead of /usr/bin/env bash
- Use command -v instead of which (not always installed)
- Use proper quoting around variables
- Use expr instead of printf to get single digit minute/hour since
  $((10#NUMBER)) is not posix compliant
- Use var=false/true instead of var=0/1
- Associative arrays are not posix compliant
  - Use arr_set and arr_get for creating/reading "array" data
- Make awk commands more readable
- Make disabled default to false

diff --git a/extra/run_nix_ta_commands b/extra/run_nix_ta_commands
--- a/extra/run_nix_ta_commands
+++ b/extra/run_nix_ta_commands
@@ -1,4 +1,4 @@
-#!/usr/bin/env bash
+#!/bin/sh
 
 # This script allows getting the Techical Add-on for Unix and Linux data into
 # Splunk from systems that are not running a Splunk Universal Forwarder.
@@ -39,11 +39,13 @@
 # ## Cron job example:
 #   * * * * * /path/to/script/run_nix_ta_commands
 
-# Ensure the logger command is available
-which logger > /dev/null 2>&1 || { echo "Error: The logger command is required for this script"; exit; }
-
 # Ensure PATH has correct paths
-export PATH=$PATH:/usr/local/sbin:/usr/local/bin
+export PATH="$PATH":/usr/local/sbin:/usr/local/bin
+
+# Ensure the logger command is available
+command -v logger > /dev/null 2>&1 || { echo "Error: The logger command is required for this script"; exit; }
+# Ensure the printf command is available
+command -v printf > /dev/null 2>&1 || { echo "Error: The printf command is required for this script"; exit; }
 
 # Example/default settings -- override in /etc/nix_ta.conf
 ta_home=/srv/TA-unix
@@ -53,76 +55,121 @@ run_minute=2
 run_hour=6
 facility=
 
+# shellcheck disable=SC1091 # quiet shellcheck about sourcing files
 [ -r /etc/nix_ta.conf ] && . /etc/nix_ta.conf
 
 # Get the current minute now to be consistent through the script run
-minute=$(printf "%d" $((10#$(date +%M))))
+# shellcheck disable=SC2003 # expr works perfectly fine
+minute=$(expr "$(date +%M)" + 0)
 # Get the current hour now to be consistent through the script run
-hour=$(printf "%d" $((10#$(date +%H))))
+# shellcheck disable=SC2003 # expr works perfectly fine
+hour=$(expr "$(date +%H)" + 0)
 # Set defaults disabling force-mode and list-mode
-force=0
-list=0
+force=false
+list=false
 
 usage() {
-  echo "usage: $(basename $0) [-h] [-f] [-l] [script]"
-  echo "          -h: print this help text"
-  echo "          -f: run all enabled scripts regardless of interval"
-  echo "          -l: list scripts, enabled status, and interval (if enabled)"
-  exit
+  echo "usage: ${0##*/} [Options] [script]"
+  echo "Options:"
+  echo "  -h: print this help text"
+  echo "  -f: run all enabled scripts regardless of interval"
+  echo "  -l: list scripts, enabled status, and interval (if enabled)"
+  exit "${1:-0}"
 }
 
 # Get the command line options
 while getopts ":hlf" opt; do
-  case $opt in
-    f) force=1 ;;
-    l) list=1 ;;
-    *) usage ;;
+  case "$opt" in
+    f) force=true ;;
+    l) list=true ;;
+    *) usage 1 ;;
   esac
 done
-shift $((OPTIND -1))
+shift $(( OPTIND - 1 ))
 
 # Function to actually run the script and pipe it to logger
 runit() {
   [ -z "$1" ] && return 1
-  if [ -x $ta_home/bin/$1.sh ]; then
+  if [ -x "$ta_home"/bin/"$1".sh ]; then
     if [ -n "$facility" ]; then
-      { $ta_home/bin/$1.sh 2> /dev/null; echo; } | logger -p $facility -t ${tag_prefix}$(echo $1|tr '[A-Z]' '[a-z]')
+      { "$ta_home"/bin/"$1".sh 2> /dev/null; echo; } | logger -p "$facility" -t "${tag_prefix}$(echo "$1"|tr '[:upper:]' '[:lower:]')"
     else
-      { $ta_home/bin/$1.sh 2> /dev/null; echo; } | logger -n $syslog_server -t ${tag_prefix}$(echo $1|tr '[A-Z]' '[a-z]')
+      { "$ta_home"/bin/"$1".sh 2> /dev/null; echo; } | logger -n "$syslog_server" -t "${tag_prefix}$(echo "$1"|tr '[:upper:]' '[:lower:]')"
     fi
   else
-    echo Could not find $1 in $ta_home/bin
+    echo "Could not find $1 in $ta_home/bin" >&2
     return 1
   fi
 }
 
+arr_set() {
+  eval "${1}_${2}=${3}"
+  eval "${1}_keys=\"\$${1}_keys $2\""
+}
+
+arr_get() {
+  eval "echo \"\$${1}_${2}\""
+}
+
 # Check the inputs.conf to see if any of the checks are disabled
-declare -A scripts
-declare -A intervals
+scripts_keys=""
+# shellcheck disable=SC2034 # this variable is used by arr_get and eval...awk
+intervals_keys=""
+
 # Load defaults first
-if [ -r $ta_home/default/inputs.conf ]; then
-  eval $(awk -F '[=#]' '
-    /^\[/{name=""}
-    /^\[script:\/\//{n=split($1,a,"/");name=gensub(/\.[a-z]+\]/,"",1,a[n]);printf "scripts[%s]=1\nintervals[%s]=60\n",name,name}
-    name!="" && $1~/(^|\s*)disabled(\s*|$)/ {disabled=gensub(/(^ | $)/,"","g",gensub(/true/,"1",1,gensub(/false/,"0",1,$2)));printf "scripts[%s]=%s\n",name,disabled}
-    name!="" && $1~/(^|\s*)interval(\s*|$)/ {interval=gensub(/(^ | $)/,"","g",$2);printf "intervals[%s]=%s\n",name,interval}
-    ' $ta_home/default/inputs.conf)
+if [ -r "$ta_home"/default/inputs.conf ]; then
+  eval "$(awk -F '[=#]' '
+    /^\[/ {
+      name = ""
+    }
+    /^\[script:\/\// {
+      n = split($1, a, "/")
+      name = a[n]
+      sub(/\.[a-z]+\]/, "", name)
+      printf "arr_set scripts %s 1\narr_set intervals %s 60\n", name, name
+    }
+    name != "" && $1 ~ /(^|\s*)disabled(\s*|$)/ {
+      gsub(/(^ | $)/, "", $2)
+      printf "arr_set scripts %s %s\n", name, $2
+    }
+    name != "" && $1 ~ /(^|\s*)interval(\s*|$)/ {
+      gsub(/(^ | $)/, "", $2)
+      printf "arr_set intervals %s %s\n", name, $2
+    }
+    ' "$ta_home"/default/inputs.conf)"
 fi
+
 # See if any defaults are overridden in the local directory
-if [ -r $ta_home/local/inputs.conf ]; then
-  eval $(awk -F '[=#]' '
-    /^\[/{name="";disabled=1;interval=60}
-    /^\[script:\/\//{n=split($1,a,"/");name=gensub(/\.[a-z]+\]/,"",1,a[n])}
-    name!="" && $1~/(^|\s*)disabled(\s*|$)/ {disabled=gensub(/(^ | $)/,"","g",gensub(/true/,"1",1,gensub(/false/,"0",1,$2)));printf "scripts[%s]=%s\n",name,disabled}
-    name!="" && $1~/(^|\s*)interval(\s*|$)/ {interval=gensub(/(^ | $)/,"","g",$2);printf "intervals[%s]=%s\n",name,interval}
-    ' $ta_home/local/inputs.conf)
+if [ -r "$ta_home"/local/inputs.conf ]; then
+  eval "$(awk -F '[=#]' '
+    /^\[/{
+      name=""
+      disabled=1
+      interval=60
+    }
+    /^\[script:\/\// {
+      n = split($1, a, "/")
+      name=a[n]
+      sub(/\.[a-z]+\]/, "", name)
+    }
+    name != "" && $1 ~ /(^|\s*)disabled(\s*|$)/ {
+      gsub(/(^ | $)/, "", $2)
+      printf "arr_set scripts %s %s\n", name, $2
+    }
+    name != "" && $1 ~ /(^|\s*)interval(\s*|$)/ {
+      gsub(/(^ | $)/, "", $2)
+      printf "arr_set intervals %s %s\n", name, $2
+    }
+    ' "$ta_home"/local/inputs.conf)"
 fi
 
 # If -l, just print the scripts
-if [ $list = 1 ]; then
-  for script in "${!scripts[@]}"; do
-    if [ "${scripts[$script]}" = "0" ]; then
-      echo "$script is enabled (${intervals[$script]} seconds)"
+if "$list"; then
+  for script in $scripts_keys; do
+    disabled=$(arr_get scripts "$script")
+    interval=$(arr_get intervals "$script")
+    if ! "${disabled:-false}"; then
+      echo "$script is enabled ($interval seconds)"
     else
       echo "$script is disabled"
     fi
@@ -131,48 +178,50 @@ if [ $list = 1 ]; then
 fi
 
 # If a script is specified on the command line, run it (even if disabled)
-if [ "$1" ]; then
-  runit $1
+if [ -n "$1" ]; then
+  runit "$1"
   exit
 fi
 
 # Without -l or -f, loop through the enabled scripts and run them at their interval
-for script in "${!scripts[@]}"; do
+for script in $scripts_keys; do
+  disabled=$(arr_get scripts "$script")
+  interval=$(arr_get intervals "$script")
   # Only run enabled scripts
-  if [ "${scripts[$script]}" = "0" ]; then
-    i=${intervals[$script]}
-    [ $i -lt 60 ] && i=60
-    min=$((i/60))
+  if ! "${disabled:-false}"; then
+    i=$interval
+    [ "$i" -lt 60 ] && i=60
+    min=$(( i / 60 ))
 
     # If -f, always run each script
-    if [ $force = 1 ]; then
-      runit $script
+    if "$force"; then
+      runit "$script"
 
     # If interval is 60 seconds or less, run every minute
-    elif [ $min -le 1 ]; then
-      runit $script
+    elif [ "$min" -le 1 ]; then
+      runit "$script"
 
     # If the current minute is divisible by the number of interval minutes, run
     # example: 600 is 5 minutes, it'll run at 0, 5, 10, 15, ... minutes
-    elif [ $((minute % min)) = 0 ]; then
-      runit $script
+    elif [ $(( minute % min )) = 0 ]; then
+      runit "$script"
 
     # If interval is an hour or more
-    elif [ $min -gt 60 ]; then
-      hr=$((i/60/60))
+    elif [ "$min" -gt 60 ]; then
+      hr=$(( i / 60 / 60 ))
 
       # If interval is 1 hour or less, run every hour on $run_minute
-      if [ $hr -le 1 ] && [ $minute = $run_minute ]; then
-        runit $script
+      if [ "$hr" -le 1 ] && [ "$minute" = "$run_minute" ]; then
+        runit "$script"
 
       # If the current hour is divisible by the number of interval hours, run
       # example: 21600 is 6 hours, it'll run at 0, 6, 12, 18 hours
-      elif [ $((hour % hr)) = 0 ] && [ $minute = $run_minute ]; then
-        runit $script
+      elif [ $(( hour % hr )) = 0 ] && [ "$minute" = "$run_minute" ]; then
+        runit "$script"
 
       # If the number of hours is 24 or more, run every day at $run_hour:$run_minute
-      elif [ $hr -ge 24 ] && [ $hour = $run_hour ] && [ $minute = $run_minute ]; then
-        runit $script
+      elif [ "$hr" -ge 24 ] && [ "$hour" = "$run_hour" ] && [ "$minute" = "$run_minute" ]; then
+        runit "$script"
       fi
     fi
   fi
